// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	dto "github.com/abattassini/tc-fiap-payment/internal/payment/infrastructure/api/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockOrderClient is an autogenerated mock type for the OrderClient type
type MockOrderClient struct {
	mock.Mock
}

type MockOrderClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderClient) EXPECT() *MockOrderClient_Expecter {
	return &MockOrderClient_Expecter{mock: &_m.Mock}
}

// GetOrder provides a mock function with given fields: orderId
func (_m *MockOrderClient) GetOrder(orderId uint) (*dto.OrderResponseDto, error) {
	ret := _m.Called(orderId)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *dto.OrderResponseDto
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*dto.OrderResponseDto, error)); ok {
		return rf(orderId)
	}
	if rf, ok := ret.Get(0).(func(uint) *dto.OrderResponseDto); ok {
		r0 = rf(orderId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.OrderResponseDto)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(orderId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderClient_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockOrderClient_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - orderId uint
func (_e *MockOrderClient_Expecter) GetOrder(orderId interface{}) *MockOrderClient_GetOrder_Call {
	return &MockOrderClient_GetOrder_Call{Call: _e.mock.On("GetOrder", orderId)}
}

func (_c *MockOrderClient_GetOrder_Call) Run(run func(orderId uint)) *MockOrderClient_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockOrderClient_GetOrder_Call) Return(_a0 *dto.OrderResponseDto, _a1 error) *MockOrderClient_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderClient_GetOrder_Call) RunAndReturn(run func(uint) (*dto.OrderResponseDto, error)) *MockOrderClient_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrderStatus provides a mock function with given fields: orderId, status
func (_m *MockOrderClient) UpdateOrderStatus(orderId uint, status int) error {
	ret := _m.Called(orderId, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, int) error); ok {
		r0 = rf(orderId, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrderClient_UpdateOrderStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrderStatus'
type MockOrderClient_UpdateOrderStatus_Call struct {
	*mock.Call
}

// UpdateOrderStatus is a helper method to define mock.On call
//   - orderId uint
//   - status int
func (_e *MockOrderClient_Expecter) UpdateOrderStatus(orderId interface{}, status interface{}) *MockOrderClient_UpdateOrderStatus_Call {
	return &MockOrderClient_UpdateOrderStatus_Call{Call: _e.mock.On("UpdateOrderStatus", orderId, status)}
}

func (_c *MockOrderClient_UpdateOrderStatus_Call) Run(run func(orderId uint, status int)) *MockOrderClient_UpdateOrderStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(int))
	})
	return _c
}

func (_c *MockOrderClient_UpdateOrderStatus_Call) Return(_a0 error) *MockOrderClient_UpdateOrderStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrderClient_UpdateOrderStatus_Call) RunAndReturn(run func(uint, int) error) *MockOrderClient_UpdateOrderStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderClient creates a new instance of MockOrderClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderClient {
	mock := &MockOrderClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
