// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entities "github.com/abattassini/tc-fiap-payment/internal/payment/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// MockPaymentRepository is an autogenerated mock type for the PaymentRepository type
type MockPaymentRepository struct {
	mock.Mock
}

type MockPaymentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentRepository) EXPECT() *MockPaymentRepository_Expecter {
	return &MockPaymentRepository_Expecter{mock: &_m.Mock}
}

// AddPayment provides a mock function with given fields: payment
func (_m *MockPaymentRepository) AddPayment(payment *entities.Payment) (*entities.Payment, error) {
	ret := _m.Called(payment)

	if len(ret) == 0 {
		panic("no return value specified for AddPayment")
	}

	var r0 *entities.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(*entities.Payment) (*entities.Payment, error)); ok {
		return rf(payment)
	}
	if rf, ok := ret.Get(0).(func(*entities.Payment) *entities.Payment); ok {
		r0 = rf(payment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(*entities.Payment) error); ok {
		r1 = rf(payment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepository_AddPayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPayment'
type MockPaymentRepository_AddPayment_Call struct {
	*mock.Call
}

// AddPayment is a helper method to define mock.On call
//   - payment *entities.Payment
func (_e *MockPaymentRepository_Expecter) AddPayment(payment interface{}) *MockPaymentRepository_AddPayment_Call {
	return &MockPaymentRepository_AddPayment_Call{Call: _e.mock.On("AddPayment", payment)}
}

func (_c *MockPaymentRepository_AddPayment_Call) Run(run func(payment *entities.Payment)) *MockPaymentRepository_AddPayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entities.Payment))
	})
	return _c
}

func (_c *MockPaymentRepository_AddPayment_Call) Return(_a0 *entities.Payment, _a1 error) *MockPaymentRepository_AddPayment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepository_AddPayment_Call) RunAndReturn(run func(*entities.Payment) (*entities.Payment, error)) *MockPaymentRepository_AddPayment_Call {
	_c.Call.Return(run)
	return _c
}

// GetPaymentByOrderId provides a mock function with given fields: orderId
func (_m *MockPaymentRepository) GetPaymentByOrderId(orderId uint) (*entities.Payment, error) {
	ret := _m.Called(orderId)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentByOrderId")
	}

	var r0 *entities.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*entities.Payment, error)); ok {
		return rf(orderId)
	}
	if rf, ok := ret.Get(0).(func(uint) *entities.Payment); ok {
		r0 = rf(orderId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(orderId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepository_GetPaymentByOrderId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPaymentByOrderId'
type MockPaymentRepository_GetPaymentByOrderId_Call struct {
	*mock.Call
}

// GetPaymentByOrderId is a helper method to define mock.On call
//   - orderId uint
func (_e *MockPaymentRepository_Expecter) GetPaymentByOrderId(orderId interface{}) *MockPaymentRepository_GetPaymentByOrderId_Call {
	return &MockPaymentRepository_GetPaymentByOrderId_Call{Call: _e.mock.On("GetPaymentByOrderId", orderId)}
}

func (_c *MockPaymentRepository_GetPaymentByOrderId_Call) Run(run func(orderId uint)) *MockPaymentRepository_GetPaymentByOrderId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockPaymentRepository_GetPaymentByOrderId_Call) Return(_a0 *entities.Payment, _a1 error) *MockPaymentRepository_GetPaymentByOrderId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepository_GetPaymentByOrderId_Call) RunAndReturn(run func(uint) (*entities.Payment, error)) *MockPaymentRepository_GetPaymentByOrderId_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePayment provides a mock function with given fields: payment
func (_m *MockPaymentRepository) UpdatePayment(payment *entities.Payment) error {
	ret := _m.Called(payment)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePayment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*entities.Payment) error); ok {
		r0 = rf(payment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentRepository_UpdatePayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePayment'
type MockPaymentRepository_UpdatePayment_Call struct {
	*mock.Call
}

// UpdatePayment is a helper method to define mock.On call
//   - payment *entities.Payment
func (_e *MockPaymentRepository_Expecter) UpdatePayment(payment interface{}) *MockPaymentRepository_UpdatePayment_Call {
	return &MockPaymentRepository_UpdatePayment_Call{Call: _e.mock.On("UpdatePayment", payment)}
}

func (_c *MockPaymentRepository_UpdatePayment_Call) Run(run func(payment *entities.Payment)) *MockPaymentRepository_UpdatePayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entities.Payment))
	})
	return _c
}

func (_c *MockPaymentRepository_UpdatePayment_Call) Return(_a0 error) *MockPaymentRepository_UpdatePayment_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentRepository_UpdatePayment_Call) RunAndReturn(run func(*entities.Payment) error) *MockPaymentRepository_UpdatePayment_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentRepository creates a new instance of MockPaymentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentRepository {
	mock := &MockPaymentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
