// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entities "github.com/abattassini/tc-fiap-payment/internal/payment/domain/entities"
	commands "github.com/abattassini/tc-fiap-payment/internal/payment/usecase/commands"

	mock "github.com/stretchr/testify/mock"
)

// MockGetPaymentUseCase is an autogenerated mock type for the GetPaymentUseCase type
type MockGetPaymentUseCase struct {
	mock.Mock
}

type MockGetPaymentUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetPaymentUseCase) EXPECT() *MockGetPaymentUseCase_Expecter {
	return &MockGetPaymentUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: command
func (_m *MockGetPaymentUseCase) Execute(command *commands.GetPaymentCommand) (*entities.Payment, error) {
	ret := _m.Called(command)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *entities.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(*commands.GetPaymentCommand) (*entities.Payment, error)); ok {
		return rf(command)
	}
	if rf, ok := ret.Get(0).(func(*commands.GetPaymentCommand) *entities.Payment); ok {
		r0 = rf(command)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(*commands.GetPaymentCommand) error); ok {
		r1 = rf(command)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetPaymentUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockGetPaymentUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - command *commands.GetPaymentCommand
func (_e *MockGetPaymentUseCase_Expecter) Execute(command interface{}) *MockGetPaymentUseCase_Execute_Call {
	return &MockGetPaymentUseCase_Execute_Call{Call: _e.mock.On("Execute", command)}
}

func (_c *MockGetPaymentUseCase_Execute_Call) Run(run func(command *commands.GetPaymentCommand)) *MockGetPaymentUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*commands.GetPaymentCommand))
	})
	return _c
}

func (_c *MockGetPaymentUseCase_Execute_Call) Return(_a0 *entities.Payment, _a1 error) *MockGetPaymentUseCase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetPaymentUseCase_Execute_Call) RunAndReturn(run func(*commands.GetPaymentCommand) (*entities.Payment, error)) *MockGetPaymentUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetPaymentUseCase creates a new instance of MockGetPaymentUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetPaymentUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetPaymentUseCase {
	mock := &MockGetPaymentUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
