// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	commands "github.com/abattassini/tc-fiap-payment/internal/payment/usecase/commands"

	mock "github.com/stretchr/testify/mock"
)

// MockGetPaymentStatusUseCase is an autogenerated mock type for the GetPaymentStatusUseCase type
type MockGetPaymentStatusUseCase struct {
	mock.Mock
}

type MockGetPaymentStatusUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetPaymentStatusUseCase) EXPECT() *MockGetPaymentStatusUseCase_Expecter {
	return &MockGetPaymentStatusUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: command
func (_m *MockGetPaymentStatusUseCase) Execute(command *commands.GetPaymentStatusCommand) (string, error) {
	ret := _m.Called(command)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*commands.GetPaymentStatusCommand) (string, error)); ok {
		return rf(command)
	}
	if rf, ok := ret.Get(0).(func(*commands.GetPaymentStatusCommand) string); ok {
		r0 = rf(command)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*commands.GetPaymentStatusCommand) error); ok {
		r1 = rf(command)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetPaymentStatusUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockGetPaymentStatusUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - command *commands.GetPaymentStatusCommand
func (_e *MockGetPaymentStatusUseCase_Expecter) Execute(command interface{}) *MockGetPaymentStatusUseCase_Execute_Call {
	return &MockGetPaymentStatusUseCase_Execute_Call{Call: _e.mock.On("Execute", command)}
}

func (_c *MockGetPaymentStatusUseCase_Execute_Call) Run(run func(command *commands.GetPaymentStatusCommand)) *MockGetPaymentStatusUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*commands.GetPaymentStatusCommand))
	})
	return _c
}

func (_c *MockGetPaymentStatusUseCase_Execute_Call) Return(_a0 string, _a1 error) *MockGetPaymentStatusUseCase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetPaymentStatusUseCase_Execute_Call) RunAndReturn(run func(*commands.GetPaymentStatusCommand) (string, error)) *MockGetPaymentStatusUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetPaymentStatusUseCase creates a new instance of MockGetPaymentStatusUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetPaymentStatusUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetPaymentStatusUseCase {
	mock := &MockGetPaymentStatusUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
