// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	commands "github.com/abattassini/tc-fiap-payment/internal/payment/usecase/commands"
	mock "github.com/stretchr/testify/mock"
)

// MockAddPaymentUseCase is an autogenerated mock type for the AddPaymentUseCase type
type MockAddPaymentUseCase struct {
	mock.Mock
}

type MockAddPaymentUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAddPaymentUseCase) EXPECT() *MockAddPaymentUseCase_Expecter {
	return &MockAddPaymentUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: command
func (_m *MockAddPaymentUseCase) Execute(command *commands.AddPaymentCommand) (string, error) {
	ret := _m.Called(command)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*commands.AddPaymentCommand) (string, error)); ok {
		return rf(command)
	}
	if rf, ok := ret.Get(0).(func(*commands.AddPaymentCommand) string); ok {
		r0 = rf(command)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*commands.AddPaymentCommand) error); ok {
		r1 = rf(command)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAddPaymentUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockAddPaymentUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - command *commands.AddPaymentCommand
func (_e *MockAddPaymentUseCase_Expecter) Execute(command interface{}) *MockAddPaymentUseCase_Execute_Call {
	return &MockAddPaymentUseCase_Execute_Call{Call: _e.mock.On("Execute", command)}
}

func (_c *MockAddPaymentUseCase_Execute_Call) Run(run func(command *commands.AddPaymentCommand)) *MockAddPaymentUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*commands.AddPaymentCommand))
	})
	return _c
}

func (_c *MockAddPaymentUseCase_Execute_Call) Return(_a0 string, _a1 error) *MockAddPaymentUseCase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAddPaymentUseCase_Execute_Call) RunAndReturn(run func(*commands.AddPaymentCommand) (string, error)) *MockAddPaymentUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAddPaymentUseCase creates a new instance of MockAddPaymentUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAddPaymentUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAddPaymentUseCase {
	mock := &MockAddPaymentUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
