// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	dto "github.com/abattassini/tc-fiap-payment/internal/payment/infrastructure/api/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockPaymentController is an autogenerated mock type for the PaymentController type
type MockPaymentController struct {
	mock.Mock
}

type MockPaymentController_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentController) EXPECT() *MockPaymentController_Expecter {
	return &MockPaymentController_Expecter{mock: &_m.Mock}
}

// CreatePayment provides a mock function with given fields: addPaymentRequest
func (_m *MockPaymentController) CreatePayment(addPaymentRequest *dto.AddPaymentRequestDto) (string, error) {
	ret := _m.Called(addPaymentRequest)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayment")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*dto.AddPaymentRequestDto) (string, error)); ok {
		return rf(addPaymentRequest)
	}
	if rf, ok := ret.Get(0).(func(*dto.AddPaymentRequestDto) string); ok {
		r0 = rf(addPaymentRequest)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*dto.AddPaymentRequestDto) error); ok {
		r1 = rf(addPaymentRequest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentController_CreatePayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePayment'
type MockPaymentController_CreatePayment_Call struct {
	*mock.Call
}

// CreatePayment is a helper method to define mock.On call
//   - addPaymentRequest *dto.AddPaymentRequestDto
func (_e *MockPaymentController_Expecter) CreatePayment(addPaymentRequest interface{}) *MockPaymentController_CreatePayment_Call {
	return &MockPaymentController_CreatePayment_Call{Call: _e.mock.On("CreatePayment", addPaymentRequest)}
}

func (_c *MockPaymentController_CreatePayment_Call) Run(run func(addPaymentRequest *dto.AddPaymentRequestDto)) *MockPaymentController_CreatePayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*dto.AddPaymentRequestDto))
	})
	return _c
}

func (_c *MockPaymentController_CreatePayment_Call) Return(_a0 string, _a1 error) *MockPaymentController_CreatePayment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentController_CreatePayment_Call) RunAndReturn(run func(*dto.AddPaymentRequestDto) (string, error)) *MockPaymentController_CreatePayment_Call {
	_c.Call.Return(run)
	return _c
}

// GetPaymentByOrderId provides a mock function with given fields: orderId
func (_m *MockPaymentController) GetPaymentByOrderId(orderId uint) (*dto.GetPaymentResponseDto, error) {
	ret := _m.Called(orderId)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentByOrderId")
	}

	var r0 *dto.GetPaymentResponseDto
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*dto.GetPaymentResponseDto, error)); ok {
		return rf(orderId)
	}
	if rf, ok := ret.Get(0).(func(uint) *dto.GetPaymentResponseDto); ok {
		r0 = rf(orderId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetPaymentResponseDto)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(orderId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentController_GetPaymentByOrderId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPaymentByOrderId'
type MockPaymentController_GetPaymentByOrderId_Call struct {
	*mock.Call
}

// GetPaymentByOrderId is a helper method to define mock.On call
//   - orderId uint
func (_e *MockPaymentController_Expecter) GetPaymentByOrderId(orderId interface{}) *MockPaymentController_GetPaymentByOrderId_Call {
	return &MockPaymentController_GetPaymentByOrderId_Call{Call: _e.mock.On("GetPaymentByOrderId", orderId)}
}

func (_c *MockPaymentController_GetPaymentByOrderId_Call) Run(run func(orderId uint)) *MockPaymentController_GetPaymentByOrderId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockPaymentController_GetPaymentByOrderId_Call) Return(_a0 *dto.GetPaymentResponseDto, _a1 error) *MockPaymentController_GetPaymentByOrderId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentController_GetPaymentByOrderId_Call) RunAndReturn(run func(uint) (*dto.GetPaymentResponseDto, error)) *MockPaymentController_GetPaymentByOrderId_Call {
	_c.Call.Return(run)
	return _c
}

// GetPaymentStatusByOrderId provides a mock function with given fields: orderId
func (_m *MockPaymentController) GetPaymentStatusByOrderId(orderId uint) (string, error) {
	ret := _m.Called(orderId)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentStatusByOrderId")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (string, error)); ok {
		return rf(orderId)
	}
	if rf, ok := ret.Get(0).(func(uint) string); ok {
		r0 = rf(orderId)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(orderId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentController_GetPaymentStatusByOrderId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPaymentStatusByOrderId'
type MockPaymentController_GetPaymentStatusByOrderId_Call struct {
	*mock.Call
}

// GetPaymentStatusByOrderId is a helper method to define mock.On call
//   - orderId uint
func (_e *MockPaymentController_Expecter) GetPaymentStatusByOrderId(orderId interface{}) *MockPaymentController_GetPaymentStatusByOrderId_Call {
	return &MockPaymentController_GetPaymentStatusByOrderId_Call{Call: _e.mock.On("GetPaymentStatusByOrderId", orderId)}
}

func (_c *MockPaymentController_GetPaymentStatusByOrderId_Call) Run(run func(orderId uint)) *MockPaymentController_GetPaymentStatusByOrderId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockPaymentController_GetPaymentStatusByOrderId_Call) Return(_a0 string, _a1 error) *MockPaymentController_GetPaymentStatusByOrderId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentController_GetPaymentStatusByOrderId_Call) RunAndReturn(run func(uint) (string, error)) *MockPaymentController_GetPaymentStatusByOrderId_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePaymentStatus provides a mock function with given fields: orderId, status
func (_m *MockPaymentController) UpdatePaymentStatus(orderId uint, status string) error {
	ret := _m.Called(orderId, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePaymentStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, string) error); ok {
		r0 = rf(orderId, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentController_UpdatePaymentStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePaymentStatus'
type MockPaymentController_UpdatePaymentStatus_Call struct {
	*mock.Call
}

// UpdatePaymentStatus is a helper method to define mock.On call
//   - orderId uint
//   - status string
func (_e *MockPaymentController_Expecter) UpdatePaymentStatus(orderId interface{}, status interface{}) *MockPaymentController_UpdatePaymentStatus_Call {
	return &MockPaymentController_UpdatePaymentStatus_Call{Call: _e.mock.On("UpdatePaymentStatus", orderId, status)}
}

func (_c *MockPaymentController_UpdatePaymentStatus_Call) Run(run func(orderId uint, status string)) *MockPaymentController_UpdatePaymentStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint), args[1].(string))
	})
	return _c
}

func (_c *MockPaymentController_UpdatePaymentStatus_Call) Return(_a0 error) *MockPaymentController_UpdatePaymentStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentController_UpdatePaymentStatus_Call) RunAndReturn(run func(uint, string) error) *MockPaymentController_UpdatePaymentStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentController creates a new instance of MockPaymentController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentController {
	mock := &MockPaymentController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
