// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	dto "github.com/abattassini/tc-fiap-payment/internal/payment/infrastructure/api/dto"
	mock "github.com/stretchr/testify/mock"
)

// MockPaymentWebhookController is an autogenerated mock type for the PaymentWebhookController type
type MockPaymentWebhookController struct {
	mock.Mock
}

type MockPaymentWebhookController_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentWebhookController) EXPECT() *MockPaymentWebhookController_Expecter {
	return &MockPaymentWebhookController_Expecter{mock: &_m.Mock}
}

// HandleWebhook provides a mock function with given fields: mercadoPagoWebhookRequest
func (_m *MockPaymentWebhookController) HandleWebhook(mercadoPagoWebhookRequest *dto.MercadoPagoWebhookNotificationRequestDTO) error {
	ret := _m.Called(mercadoPagoWebhookRequest)

	if len(ret) == 0 {
		panic("no return value specified for HandleWebhook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*dto.MercadoPagoWebhookNotificationRequestDTO) error); ok {
		r0 = rf(mercadoPagoWebhookRequest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentWebhookController_HandleWebhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleWebhook'
type MockPaymentWebhookController_HandleWebhook_Call struct {
	*mock.Call
}

// HandleWebhook is a helper method to define mock.On call
//   - mercadoPagoWebhookRequest *dto.MercadoPagoWebhookNotificationRequestDTO
func (_e *MockPaymentWebhookController_Expecter) HandleWebhook(mercadoPagoWebhookRequest interface{}) *MockPaymentWebhookController_HandleWebhook_Call {
	return &MockPaymentWebhookController_HandleWebhook_Call{Call: _e.mock.On("HandleWebhook", mercadoPagoWebhookRequest)}
}

func (_c *MockPaymentWebhookController_HandleWebhook_Call) Run(run func(mercadoPagoWebhookRequest *dto.MercadoPagoWebhookNotificationRequestDTO)) *MockPaymentWebhookController_HandleWebhook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*dto.MercadoPagoWebhookNotificationRequestDTO))
	})
	return _c
}

func (_c *MockPaymentWebhookController_HandleWebhook_Call) Return(_a0 error) *MockPaymentWebhookController_HandleWebhook_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentWebhookController_HandleWebhook_Call) RunAndReturn(run func(*dto.MercadoPagoWebhookNotificationRequestDTO) error) *MockPaymentWebhookController_HandleWebhook_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentWebhookController creates a new instance of MockPaymentWebhookController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentWebhookController(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentWebhookController {
	mock := &MockPaymentWebhookController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
