// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	commands "github.com/abattassini/tc-fiap-payment/internal/payment/usecase/commands"
	mock "github.com/stretchr/testify/mock"
)

// MockUpdatePaymentUseCase is an autogenerated mock type for the UpdatePaymentUseCase type
type MockUpdatePaymentUseCase struct {
	mock.Mock
}

type MockUpdatePaymentUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdatePaymentUseCase) EXPECT() *MockUpdatePaymentUseCase_Expecter {
	return &MockUpdatePaymentUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: command
func (_m *MockUpdatePaymentUseCase) Execute(command *commands.UpdatePaymentStatusCommand) error {
	ret := _m.Called(command)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*commands.UpdatePaymentStatusCommand) error); ok {
		r0 = rf(command)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUpdatePaymentUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockUpdatePaymentUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - command *commands.UpdatePaymentStatusCommand
func (_e *MockUpdatePaymentUseCase_Expecter) Execute(command interface{}) *MockUpdatePaymentUseCase_Execute_Call {
	return &MockUpdatePaymentUseCase_Execute_Call{Call: _e.mock.On("Execute", command)}
}

func (_c *MockUpdatePaymentUseCase_Execute_Call) Run(run func(command *commands.UpdatePaymentStatusCommand)) *MockUpdatePaymentUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*commands.UpdatePaymentStatusCommand))
	})
	return _c
}

func (_c *MockUpdatePaymentUseCase_Execute_Call) Return(_a0 error) *MockUpdatePaymentUseCase_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUpdatePaymentUseCase_Execute_Call) RunAndReturn(run func(*commands.UpdatePaymentStatusCommand) error) *MockUpdatePaymentUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdatePaymentUseCase creates a new instance of MockUpdatePaymentUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdatePaymentUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdatePaymentUseCase {
	mock := &MockUpdatePaymentUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
