// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	commands "github.com/abattassini/tc-fiap-payment/internal/payment/usecase/commands"

	mock "github.com/stretchr/testify/mock"
)

// MockHandleWebhookUseCase is an autogenerated mock type for the HandleWebhookUseCase type
type MockHandleWebhookUseCase struct {
	mock.Mock
}

type MockHandleWebhookUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandleWebhookUseCase) EXPECT() *MockHandleWebhookUseCase_Expecter {
	return &MockHandleWebhookUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: command
func (_m *MockHandleWebhookUseCase) Execute(command commands.HandleWebhookCommand) error {
	ret := _m.Called(command)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(commands.HandleWebhookCommand) error); ok {
		r0 = rf(command)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHandleWebhookUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockHandleWebhookUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - command commands.HandleWebhookCommand
func (_e *MockHandleWebhookUseCase_Expecter) Execute(command interface{}) *MockHandleWebhookUseCase_Execute_Call {
	return &MockHandleWebhookUseCase_Execute_Call{Call: _e.mock.On("Execute", command)}
}

func (_c *MockHandleWebhookUseCase_Execute_Call) Run(run func(command commands.HandleWebhookCommand)) *MockHandleWebhookUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(commands.HandleWebhookCommand))
	})
	return _c
}

func (_c *MockHandleWebhookUseCase_Execute_Call) Return(_a0 error) *MockHandleWebhookUseCase_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandleWebhookUseCase_Execute_Call) RunAndReturn(run func(commands.HandleWebhookCommand) error) *MockHandleWebhookUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHandleWebhookUseCase creates a new instance of MockHandleWebhookUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandleWebhookUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandleWebhookUseCase {
	mock := &MockHandleWebhookUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
