// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/abattassini/tc-fiap-payment/internal/payment/infrastructure/api/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockMercadoPagoGateway is an autogenerated mock type for the MercadoPagoGateway type
type MockMercadoPagoGateway struct {
	mock.Mock
}

type MockMercadoPagoGateway_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMercadoPagoGateway) EXPECT() *MockMercadoPagoGateway_Expecter {
	return &MockMercadoPagoGateway_Expecter{mock: &_m.Mock}
}

// GenerateQRCode provides a mock function with given fields: ctx, request
func (_m *MockMercadoPagoGateway) GenerateQRCode(ctx context.Context, request dto.CreateQRCodeDTO) (dto.QRCodeResponseDto, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GenerateQRCode")
	}

	var r0 dto.QRCodeResponseDto
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateQRCodeDTO) (dto.QRCodeResponseDto, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.CreateQRCodeDTO) dto.QRCodeResponseDto); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(dto.QRCodeResponseDto)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.CreateQRCodeDTO) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMercadoPagoGateway_GenerateQRCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateQRCode'
type MockMercadoPagoGateway_GenerateQRCode_Call struct {
	*mock.Call
}

// GenerateQRCode is a helper method to define mock.On call
//   - ctx context.Context
//   - request dto.CreateQRCodeDTO
func (_e *MockMercadoPagoGateway_Expecter) GenerateQRCode(ctx interface{}, request interface{}) *MockMercadoPagoGateway_GenerateQRCode_Call {
	return &MockMercadoPagoGateway_GenerateQRCode_Call{Call: _e.mock.On("GenerateQRCode", ctx, request)}
}

func (_c *MockMercadoPagoGateway_GenerateQRCode_Call) Run(run func(ctx context.Context, request dto.CreateQRCodeDTO)) *MockMercadoPagoGateway_GenerateQRCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dto.CreateQRCodeDTO))
	})
	return _c
}

func (_c *MockMercadoPagoGateway_GenerateQRCode_Call) Return(_a0 dto.QRCodeResponseDto, _a1 error) *MockMercadoPagoGateway_GenerateQRCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMercadoPagoGateway_GenerateQRCode_Call) RunAndReturn(run func(context.Context, dto.CreateQRCodeDTO) (dto.QRCodeResponseDto, error)) *MockMercadoPagoGateway_GenerateQRCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMercadoPagoGateway creates a new instance of MockMercadoPagoGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMercadoPagoGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMercadoPagoGateway {
	mock := &MockMercadoPagoGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
