// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	entities "github.com/abattassini/tc-fiap-payment/internal/payment/domain/entities"
	dto "github.com/abattassini/tc-fiap-payment/internal/payment/infrastructure/api/dto"

	mock "github.com/stretchr/testify/mock"
)

// MockPaymentPresenter is an autogenerated mock type for the PaymentPresenter type
type MockPaymentPresenter struct {
	mock.Mock
}

type MockPaymentPresenter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentPresenter) EXPECT() *MockPaymentPresenter_Expecter {
	return &MockPaymentPresenter_Expecter{mock: &_m.Mock}
}

// Present provides a mock function with given fields: payment
func (_m *MockPaymentPresenter) Present(payment *entities.Payment) *dto.GetPaymentResponseDto {
	ret := _m.Called(payment)

	if len(ret) == 0 {
		panic("no return value specified for Present")
	}

	var r0 *dto.GetPaymentResponseDto
	if rf, ok := ret.Get(0).(func(*entities.Payment) *dto.GetPaymentResponseDto); ok {
		r0 = rf(payment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.GetPaymentResponseDto)
		}
	}

	return r0
}

// MockPaymentPresenter_Present_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Present'
type MockPaymentPresenter_Present_Call struct {
	*mock.Call
}

// Present is a helper method to define mock.On call
//   - payment *entities.Payment
func (_e *MockPaymentPresenter_Expecter) Present(payment interface{}) *MockPaymentPresenter_Present_Call {
	return &MockPaymentPresenter_Present_Call{Call: _e.mock.On("Present", payment)}
}

func (_c *MockPaymentPresenter_Present_Call) Run(run func(payment *entities.Payment)) *MockPaymentPresenter_Present_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*entities.Payment))
	})
	return _c
}

func (_c *MockPaymentPresenter_Present_Call) Return(_a0 *dto.GetPaymentResponseDto) *MockPaymentPresenter_Present_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentPresenter_Present_Call) RunAndReturn(run func(*entities.Payment) *dto.GetPaymentResponseDto) *MockPaymentPresenter_Present_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentPresenter creates a new instance of MockPaymentPresenter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentPresenter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentPresenter {
	mock := &MockPaymentPresenter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
